env:
    - TZ="Australia/Hobart"

before_script:
    - export JAVA_OPTS="-Xmx1G -Xms512m -XX:PermSize=64m -XX:MaxPermSize=512m"

before_install:
    - sudo apt-get install tzdata
    - sudo dpkg-reconfigure tzdata
    
language: groovy

jdk:
    - openjdk7

notifications:
  email: false
  