before_script: sudo echo 'Australia/Hobart' > /etc/timezone

before_install:
    - sudo apt-get install tzdata
    - sudo dpkg-reconfigure tzdata
    
language: groovy

jdk:
    - openjdk7

notifications:
  email: false
  